### ISSUE TITLE
License for assets

### ISSUE THREAD

**Issue by otakustay** [U1805/momotalk#15]
Happy to see this great project, may I ask which license is this project based on, may I reference or copy fonts, images and icons in my own projects for free?

**Comment by U1805** [comment]
Thank you for your interest in the project! However, due to potential copyright restrictions related to the Blue Archive game, I do not intend to add an open-source license, similar to what [schale.gg](https://github.com/lonqie/SchaleDB) and [closure-talk](https://github.com/ClosureTalk/closure-talk) have done. 
Nevertheless, I won't actually object to you using these assets in your project XD
