### ISSUE TITLE
添加差分表情支持

### ISSUE THREAD

**Issue by CNflysky** [U1805/momotalk#16]
是否考虑加入学生差分表情图支持呢？
网站设计的很还原游戏，⭐了

**Comment by U1805** [comment]
谢谢。这个功能其实一直在我的 todo list 里，不过主要的问题在表情差分的数据来源

目前我只看到 [gamekee](https://ba.gamekee.com/) 上有提供表情差分数据，不知道有没有其他的方案可以选择，想请问一下你平时会去哪里找差分呀？

**Comment by nfnfgo** [comment]
Not sure if this is helpful but I also saw that character portrait face variations img provided in **student appreciatin mode** on [KivoWiki](https://kivo.wiki/) and seems those imgs are open for download lol

![image](https://github.com/U1805/momotalk/assets/61616918/3d488e15-8ed3-4c0a-819b-d43ba1bd2061)


I still believe this feature is worth considering for addtion to the project, since it's quite a common senario that users wants to incorporate different student face imgs into the chat to add more fun or express the student emotions more accurately and vividly

**Comment by U1805** [comment]
@nfnfgo 

Thank you for your suggestion! In fact, I implemented and committed that feature last month. That feature is considered as a kind of special stickers now, and you can check out the student appreciatin mode by **clicking on the avatar in the input bar**, 

However, it seems I forgot to update this feature in the documentation 😂. I appreciate your keen observation, and I'll make sure to add it to the instructions. If you encounter any issues or have further suggestions, feel free to let me know!

![image](https://github.com/U1805/momotalk/assets/45514638/ee6a461e-2631-4c3e-8b6c-806df775381b)
