### ISSUE TITLE
[enhancement] Allow inserting message at the middle of the chat

### ISSUE THREAD

**Issue by nfnfgo** [U1805/momotalk#18]
Currently it seems there is no direct way to insert a new message at a certain position (for example after a certain message). Though it do have a workaround that adding a new message at the end and then drag it to the expected place, but this is not quite feasible when chat list are becoming longer and longer.

If it's possible to allow user to insert a new message at the middle of the chat history? For example one possible solution is to show an "Insert After" button when hovering over messages or showing "Insert Here" button when hovering between two message etc. But anyway this is just my own thought and there could be a better way to achieve this feature 😂

**Comment by U1805** [comment]
> but this is not quite feasible when chat list are becoming longer and longer.

You're absolutely right. I haven't encountered scenarios with very long conversations myself, so I might have overlooked the challenges that could arise as the list grows. (ノдT)

I've been cautious about introducing a potentially complex insertion action, as I was concerned it might not be as intuitive as other actions like dragging or editing. I want to ensure a smooth user experience without sacrificing usability.

My current idea is to add **an "Insert" button beneath the delete button** in each message bubble. When clicked, it would set a flag, allowing the user insert after that specific message. Since I assume insertions might not be a frequent action, the flag would be automatically canceled after the next input or could be manually canceled by clicking the button again.

I plan to work on implementing this feature next week. Thank you for bringing up this suggestion! If you have any more suggestions or thoughts, feel free to share them.

**Comment by nfnfgo** [comment]
> My current idea is to add an "Insert" button beneath the delete button in each message bubble. When clicked, it would set a flag, allowing the user to insert after that specific message. Since I assume insertions might not be a frequent action, the flag would be automatically canceled after the next input or could be manually canceled by clicking the button again.

This is a good idea, however, in this scenario if a user wants to insert a message, the complete workflow would be:

1. Find the place where they want to insert a new message.
2. Click on the "Insert" button as mentioned.
3. Edit the new message.
4. Click "Send" (or press `Enter` on the keyboard).

My thought is that maybe instead of introducing something less intuitive like a "cursor" to specify the insertion place next time, it might be better to directly show something like a **"Send Message to Here" button** (since this name is quite long we could initially use an `insert` or `send` icon, and, if necessary, we could consider showing a pop-up with full button feature description when the user hovering over this button)

Then when this button is clicked, it will act similarly to the "Send" button on the message edit bar _(since they both send a new message into the chat list)_, with the only difference being that this time the message **will NOT be added to the end of the list** but will be **inserted after the message** where the "Send Message to Here" button was clicked.

If using this implementation, when user want to insert a new message to certain place, they only need to:

1. Edit the message (but don't press Enter or click the "Send" button this time)
2. Find the position they want to insert a new message to
3. Click "Send Message to Here" button

At the end it's only my very personal thought but I think the second way looks more convenient and more intuitive to me and it avoid introducing a new cursor-like conception to users

**Comment by U1805** [comment]
Wow, I must say your approach is indeed quite clever. Essentially, the logic for inserting into the middle remains consistent with appending to the end. The only difference lies in the location of the send button – one appears next to the message bubble, while the other is positioned in the input bar. I think I'll give this method a try.

Regarding the hover effect you mentioned, there might be some issues on mobile devices. Even though the current version of this project might not be very mobile-friendly, I still want to minimize potential styling conflicts on these devices. Therefore, I'm not planning to implement a pop-up window. Instead, I'll do my best to find an intuitive icon or symbol that conveys the semantic meaning without relying on hover effects.

**Comment by U1805** [comment]
i've thought about it some more, it seems that your proposed solution may not address the scenario of inserting images. Do you have any suggestions for handling that situation?  (´･_･`)

**Comment by nfnfgo** [comment]
To be frankly I didn't consider about the image insertion before 😭 And as you mentioned, my approach need all info of the message is known when clicking the action button, which means it may stuck when user want to insert an image since when user want to add an image and click the "Add Image" button, the actual data is still unknown.

I just take some time to think about this issue and for now I can think out two different solutions.

## One more "Insert Image Button"

This means in addtion to "Send Message Here" button, there should be one more button that allow user to insert image directly after a message. However imo this solution is not so elegant and simple, moreover, this solution means if in the future you want to expand the type of message, then there is a possiblitiy that more and more button need to be added following to the message and in my opinion this will definitely make the UI and edit logic a mass which is not acceptable.

## Drag and drop

As you said before, drag and drop is really a great interation way for user which is convenient ,intuitive and also perfectly compatible with mobile devices at the same time. 

There are some prerequisite in order to implement this approach:

- All messages should have an _initial content_ or some _placeholder content_ (For example, text message has some initial text, and for image we could showing the placeholder image when image are not being specified yet).
- All messages should be allowed to be re-edit after being added to the chat list. (Currently all messages type are satifisfied with this condition, for example user are allowed to change the text of the existing message, and the image message could also be replaced by click the image itself). 

Then this message suggest that the buttons at the bottom message editing list should be draggable.

![image](https://github.com/U1805/momotalk/assets/61616918/2fcb17bd-b50d-47e4-aa94-b436058cf5f6)

Then when user want to insert a certain type of message to certain page, they only need to drag the corresponding type of button to the specified position. (Here there should be an indicator, for example, a placeholder block or a horizontal line tells user where this message is going to be added to)

Taking into consideration that this approach may require a big change to currently existing code and interaction logic, there also has a more conservative approach that is to allow user add image by drag file to the specified position (this is a valid complementation to my previous "Send to here"approach while not require adding these completely new drag-and-drop logic to those buttons)

**Comment by U1805** [comment]
Yes, both approaches have their shortcomings. In the case of the second solution, while it is intuitive, it might not be as convenient as the initial proposal. 

However, I appreciate your idea of using an **"indicator."** I'm considering combining this concept with the initial approach. Instead of implementing Drag and Drop, I'll replace it with a Click on the insertion button. When the user clicks the insert button, I'll **display a line between that message bubble and the next one**, indicating that the next message will be inserted at this position. All other inster logic remains the same as appending to the end. This approach smoothly can extend all message types from appending at the end to inserting in the middle.


1. Find the place where they want to insert a new message.
2. Click on the "Insert" button as mentioned, and an indicator line will appear below it.
3. Send the new message/Send the image as usual


Thank you again for your valuable inputs. I'll implement by this approaches soon.

**Comment by U1805** [comment]
This feature is done! (〃∀〃)
