### ISSUE TITLE
Create How-to-use.md Japanese Version

### ISSUE THREAD

**Issue by dfaw20** [U1805/momotalk#23]
- [ ] Create a new version of the document in Japanese.

https://github.com/U1805/momotalk/blob/main/docs/How-to-use.md

**Comment by dfaw20** [comment]
I recently noticed that the new multilingual support has been completed so I have updated the title

**Comment by U1805** [comment]
Hi! It seems like you've encountered some problems. The good news is that I've tried using the new ChatGPT-4o for localization translation, and the results turned out well. Therefore, I'll be closing this issue. If you come across any errors in the machine translation, feel free to continue raising issues or submitting pull requests to help rectify them!

**Comment by dfaw20** [comment]
Sorry for the late reply, I've been busy lately and haven't been able to respond, I'm glad the translation by ChatGPT worked
